In [20]:
import torch
from torchvision.transforms import Normalize

pixel_values = torch.randint(0, 255, (1, 1, 32))
pixel_values = pixel_values / 255
pixel_values

tensor([[[0.4980, 0.1255, 0.9725, 0.3961, 0.8275, 0.6392, 0.5686, 0.5255,
          0.0941, 0.2588, 0.0392, 0.5490, 0.4980, 0.6392, 0.7882, 0.7647,
          0.3961, 0.8784, 0.7725, 0.1059, 0.4118, 0.8863, 0.1255, 0.3059,
          0.1137, 0.8863, 0.7922, 0.7569, 0.9961, 0.0314, 0.3294, 0.9882]]])

In [24]:
normalizer = Normalize(mean=0.5, std=0.5)
norm_pixel = normalizer(pixel_values)
norm_pixel

tensor([[[-0.0039, -0.7490,  0.9451, -0.2078,  0.6549,  0.2784,  0.1373,
           0.0510, -0.8118, -0.4824, -0.9216,  0.0980, -0.0039,  0.2784,
           0.5765,  0.5294, -0.2078,  0.7569,  0.5451, -0.7882, -0.1765,
           0.7725, -0.7490, -0.3882, -0.7725,  0.7725,  0.5843,  0.5137,
           0.9922, -0.9373, -0.3412,  0.9765]]])

In [27]:
norm_pixel = norm_pixel.reshape(1, 1, 4, 8)
norm_pixel

tensor([[[[-0.0039, -0.7490,  0.9451, -0.2078,  0.6549,  0.2784,  0.1373,
            0.0510],
          [-0.8118, -0.4824, -0.9216,  0.0980, -0.0039,  0.2784,  0.5765,
            0.5294],
          [-0.2078,  0.7569,  0.5451, -0.7882, -0.1765,  0.7725, -0.7490,
           -0.3882],
          [-0.7725,  0.7725,  0.5843,  0.5137,  0.9922, -0.9373, -0.3412,
            0.9765]]]])

In [58]:
import random

pixel_values = [random.randint(0, 255) for i in range(8)]
pixel_values = torch.as_tensor(pixel_values, dtype=torch.float).view(1, 1, -1)
pixel_values, pixel_values.shape

(tensor([[[111., 156.,  64.,  45., 168., 192., 130., 114.]]]),
 torch.Size([1, 1, 8]))

In [63]:
from torchvision.transforms import Normalize

normalize = Normalize(mean=0.5, std=0.5)
norm_pixel_values = normalize(pixel_values / 255)
norm_pixel_values, norm_pixel_values.shape

(tensor([[[-0.1294,  0.2235, -0.4980, -0.6471,  0.3176,  0.5059,  0.0196,
           -0.1059]]]),
 torch.Size([1, 1, 8]))

In [77]:
pad_pixel_values = torch.nn.functional.pad(norm_pixel_values, (0, 2, 0, 0))
pad_pixel_values, pad_pixel_values.shape

(tensor([[[-0.1294,  0.2235, -0.4980, -0.6471,  0.3176,  0.5059,  0.0196,
           -0.1059,  0.0000,  0.0000]]]),
 torch.Size([1, 1, 10]))